### ISSUE TITLE
Unable to read rssi value

### ISSUE THREAD

**Issue by rskfam** [radiosd/PlutoSdr#5]
I ran a simple script to print the rssi but it threw an exception. Both the python script and printout of the exception message are shown below.
Should the return statement be  "self._phy_rx.attrs['rssi'].value" ?
Thanks for looking into it.

Python script
*****************
#!/usr/bin/env python2
# _*_ coding: utf-8 _*_
#

from __future__ import print_function
from pluto.pluto_sdr import PlutoSdr

sdr = PlutoSdr('ip:pluto.local')
print("RSSI =", sdr.rsssi)

Exception thrown:
*********************
Traceback (most recent call last):
  File "rssi_bug.py", line 9, in <module>
    print("RSSI =", sdr.rsssi)
  File "/usr/local/lib/python2.7/dist-packages/pluto/pluto_sdr.py", line 201, in _get_rx_rssi
    return self._phy.channels[5].attrs['rssi'].value
AttributeError: 'PlutoSdr' object has no attribute '_phy'

**Comment by radiosd** [comment]
Dear rskfab,  Thank you for the interest in my work and sorry to be so late.  I have just realised that these e-mails go to 'promotions' in my mail client and they are not routinely looked at, especially when I'm busy!

The error is in the underscore.  The code should be 
self.phy.channels[5].attrs['rssi'].value

However a better way, because I changed things  to eliminate the unhelpful references to numbered channels, is to use a suitably named property. So this should be equivalent
self.phy_rx.attrs['rssi'].value

Hope that helps.  I will push an update with your improvements when I get a chance.

regards Richard
