### ISSUE TITLE
OSX High Sierra Install Error

### ISSUE THREAD

**Issue by cpbridges** [radiosd/PlutoSdr#6]
Hi Folks,

I have libiio installed OK, rsdlib tests OK, and the PlutoSDR fails on the following test. I'm running OSX High Sierra, running condo / macports. Here's the error and I'm guessing there's no OSX handler / path?

Any ideas, thoughts? 73s Chris

```
(py37) Chris-MacBookAir:test chrisbridges$ python testPlutoSdr.py 
Traceback (most recent call last):
  File "testPlutoSdr.py", line 17, in <module>
    import iio
  File "/Users/chrisbridges/miniconda3/envs/py37/lib/python3.7/site-packages/iio.py", line 62, in <module>
    use_errno = True, use_last_error = True)
  File "/Users/chrisbridges/miniconda3/envs/py37/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libiio.so.0, 6): image not found
(py37) Chris-MacBookAir:test chrisbridges$ 
```

**Comment by radiosd** [comment]
Dear Chris, Thank you for the interest in my work.

From the trace it looks like the iio lib is not installed properly.  From a python console try to import it on its own. i.e.
import iio

If that works the with Pluto connected try
iio.scan_contexts()
That should return a dict with information on all iio devices and pluto should be in the dict.

hope that helps Richard

**Comment by cpbridges** [comment]
That's almost correct but I've found a route through. I've installed from: https://github.com/analogdevicesinc/libiio which are precompiled binaries. 

```
(py37) Chris-MacBookAir:~ chrisbridges$ iio_info -s
Library version: 0.18 (git tag: v0.18)
Compiled with backends: xml ip usb
Available contexts:
	0: 0456:b673 (Analog Devices Inc. PlutoSDR (ADALM-PLUTO)), serial=104400b8399100180d0004001f8a65f6d6 [usb:250.5.5]
```

I then used pip to install iio. And then it all sprung into life. Perhaps the readme can be updated to include "pip install iio" and "pip install pyadi-iio". After this the import iio works OK but the test in PlutoSdr tests fail:
```
(py37) Chris-MacBookAir:test chrisbridges$ python testPlutoSdr.py 
testPlutoSdr requires a pluto device connected
```
My pluto exists from my Network Manager:
"PlutoSDR _ADALM_PLUTO_ is currently active and has the IP address 192.168.2.2."

I also note a mismatch in the libiio functions:
```
>>> iio.
iio.ARRAY(                  iio.c_uint(
iio.ArgumentError(          iio.c_uint16(
iio.Array(                  iio.c_uint32(
iio.BigEndianStructure(     iio.c_uint64(
iio.CDLL(                   iio.c_uint8(
iio.CFUNCTYPE(              iio.c_ulong(
iio.DEFAULT_MODE            iio.c_ulonglong(
iio.LibraryLoader(          iio.c_ushort(
iio.LittleEndianStructure(  iio.c_void_p(
iio.POINTER(                iio.c_voidp(
iio.PYFUNCTYPE(             iio.c_wchar(
iio.PyDLL(                  iio.c_wchar_p(
iio.RTLD_GLOBAL             iio.cast(
iio.RTLD_LOCAL              iio.cdll
iio.SetPointerType(         iio.create_string_buffer(
iio.Structure(              iio.create_unicode_buffer(
iio.Union(                  iio.ctypes
iio.addressof(              iio.find_library(
iio.alignment(              iio.get_errno(
iio.byref(                  iio.iioread(
iio.c_bool(                 iio.iiosave(
iio.c_buffer(               iio.libc
iio.c_byte(                 iio.libiio
iio.c_char(                 iio.memmove(
iio.c_char_p(               iio.memset(
iio.c_double(               iio.np
iio.c_float(                iio.os
iio.c_int(                  iio.pointer(
iio.c_int16(                iio.py_object(
iio.c_int32(                iio.pydll
iio.c_int64(                iio.pythonapi
iio.c_int8(                 iio.read(
iio.c_long(                 iio.resize(
iio.c_longdouble(           iio.set_errno(
iio.c_longlong(             iio.sizeof(
iio.c_short(                iio.string_at(
iio.c_size_t(               iio.write(
iio.c_ssize_t(              iio.wstring_at(
iio.c_ubyte(  
```
Any ideas? 73s Chris

**Comment by radiosd** [comment]
I am pleased that you are making progress.  However I think the problem is still associated with iio, for which I am not an expert in.  The library has number of backends and I think you are missing the 'local' one which is why pluto is  not being detected.  To see which backends are installed, from a command prompt type:
iio-config | grep backends
That should produce one or more items in a list.  I suspect that local will be missing others are usb, ip for example.
You can also check that the IP for pluto should have worked by using:
ping pluto.local
Which should show some send and receive bytes data.

To fix things you can see how to install the local backend.  I am afraid I do not know how to do this, it happened on my machines (windows, linux) from the basic install.  Also I was under the impression that the local discover was a 'universal' mechanism, but obviously I was mistaken

The alternative is to use one of the other ways to connect to pluto.  Information from the iio-config and iio.scanContexts() should help.  For example, I also have the usb backend installed by default on my windows machine and the scanContexts() command shows the address as usb:6.5.5.  That will be different on different computers, but the principle should work.  The pluto_sdr file has a constant that can be changed to the address you find.  For example:
PLUTO_ID = 'usb:6.5.5'
Then the tests should work.

Another possibility is, if the ip backend is available then you can use the IP that you have already found in a similar way:
PLUTO_ID = 'ip:192.168.2.2'

I hope this helps.  There is support for libiio on the ADI engineers zone website.

73 Richard
